os:
  - linux
  - osx

env:
  NASHPATH: "/tmp/nash"

language: go
sudo: false

go:
  - tip
install:
  - go get -v github.com/NeowayLabs/nash/cmd/nash
  - cd $GOPATH/src/github.com/NeowayLabs/nash/cmd/nash && git checkout multiple-returns && make install

script:
  - nash -c "make test"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/52ad02845e880cdca2cf
    on_success: change
    on_failure: always
    on_start: never
  email:
    - tiago.natel@neoway.com.br
    - tiago.katcipis@neoway.com.br
    - vitor.arins@neoway.com.br
